name: Atualiza README (timestamp)

on:
  schedule:
    - cron: '0 9 * * *' # todo dia às 09:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Atualiza timestamp no README
        run: |
          dt=$(date -u +'%Y-%m-%d %H:%M:%S')
          sed -i "s/<!--TIMESTAMP-->.*<!--\/TIMESTAMP-->/<!--TIMESTAMP-->${dt}<!--\/TIMESTAMP-->/" README.md

      - name: Commit & push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "chore(readme): update timestamp ${dt}" || echo "nada a commitar"
          git push